"""add candidate supported evidence store infrastructure

Revision ID: 0004_candidate_supported_store
Revises: 0003_security_foundation
"""
from alembic import op
import sqlalchemy as sa
revision="0004_candidate_supported_store";down_revision="0003_security_foundation";branch_labels=None;depends_on=None

def _scope():
 return [sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("tenant_id",sa.Uuid(),nullable=False),sa.Column("case_id",sa.Uuid(),nullable=False)]
def upgrade():
 op.create_table("supported_processing_runs",*_scope(),sa.Column("evidence_source_id",sa.Uuid(),nullable=False),sa.Column("purpose_key",sa.String(128),nullable=False),sa.Column("requested_at",sa.DateTime(timezone=True),nullable=False),sa.Column("requested_by_actor_id",sa.Uuid(),nullable=False),sa.Column("correlation_id",sa.Uuid(),nullable=False),sa.Column("authorization_policy_id",sa.Uuid(),nullable=False),sa.Column("authorization_policy_version",sa.Integer(),nullable=False),sa.ForeignKeyConstraint(["tenant_id"],["security_tenants.id"]),sa.ForeignKeyConstraint(["case_id","tenant_id"],["security_cases.id","security_cases.tenant_id"]),sa.ForeignKeyConstraint(["evidence_source_id"],["security_evidence_sources.id"]))
 op.create_table("evidence_parser_identities",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("parser_id",sa.String(128),nullable=False),sa.Column("parser_version",sa.String(64),nullable=False),sa.Column("artifact_family",sa.String(128),nullable=False),sa.Column("contract_version",sa.String(64),nullable=False),sa.Column("registry_state",sa.String(32),nullable=False),sa.Column("declaration_reference",sa.String(255),nullable=False),sa.UniqueConstraint("parser_id","parser_version"))
 op.create_table("supported_source_artifacts",*_scope(),sa.Column("evidence_source_id",sa.Uuid(),nullable=False),sa.Column("processing_run_id",sa.Uuid(),nullable=False),sa.Column("evidence_uuid",sa.Uuid(),nullable=False),sa.Column("artifact_family_key",sa.String(128),nullable=False),sa.ForeignKeyConstraint(["tenant_id"],["security_tenants.id"]),sa.ForeignKeyConstraint(["case_id","tenant_id"],["security_cases.id","security_cases.tenant_id"]),sa.ForeignKeyConstraint(["processing_run_id"],["supported_processing_runs.id"]))
 op.create_table("supported_source_locators",*_scope(),sa.Column("source_artifact_id",sa.Uuid(),nullable=False),sa.Column("locator_kind",sa.String(128),nullable=False),sa.Column("raw_value",sa.Text(),nullable=False),sa.Column("normalized_value",sa.Text(),nullable=False),sa.Column("normalization_method",sa.String(128),nullable=False),sa.ForeignKeyConstraint(["source_artifact_id"],["supported_source_artifacts.id"]))
 op.create_table("evidence_schema_fingerprint_observations",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("source_artifact_id",sa.Uuid(),nullable=False),sa.Column("processing_run_id",sa.Uuid(),nullable=False),sa.Column("parser_identity_id",sa.Uuid()),sa.Column("profile_id",sa.String(128),nullable=False),sa.Column("profile_version",sa.String(64),nullable=False),sa.Column("canonical_input_reference",sa.Text(),nullable=False),sa.Column("sha256_digest",sa.String(64),nullable=False),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("limitations",sa.JSON(),nullable=False),sa.ForeignKeyConstraint(["source_artifact_id"],["supported_source_artifacts.id"]),sa.ForeignKeyConstraint(["processing_run_id"],["supported_processing_runs.id"]),sa.ForeignKeyConstraint(["parser_identity_id"],["evidence_parser_identities.id"]))
 op.create_table("evidence_typed_representations",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("state",sa.String(32),nullable=False),sa.Column("type_id",sa.String(128),nullable=False),sa.Column("serialization_profile_id",sa.String(128),nullable=False),sa.Column("serialization_profile_version",sa.String(64),nullable=False),sa.Column("serialized_value",sa.Text()),sa.Column("failure_code",sa.String(128)))
 op.create_table("evidence_value_transformations",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("method_id",sa.String(128),nullable=False),sa.Column("method_version",sa.String(64),nullable=False),sa.Column("processing_run_id",sa.Uuid(),nullable=False),sa.Column("parser_identity_id",sa.Uuid()),sa.Column("transformed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("limitations",sa.JSON(),nullable=False),sa.ForeignKeyConstraint(["processing_run_id"],["supported_processing_runs.id"]),sa.ForeignKeyConstraint(["parser_identity_id"],["evidence_parser_identities.id"]))
 op.create_table("evidence_typed_value_observations",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("source_artifact_id",sa.Uuid(),nullable=False),sa.Column("processing_run_id",sa.Uuid(),nullable=False),sa.Column("parser_identity_id",sa.Uuid()),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("raw_representation_id",sa.Uuid(),nullable=False),sa.Column("normalized_representation_id",sa.Uuid()),sa.Column("transformation_id",sa.Uuid()),sa.ForeignKeyConstraint(["source_artifact_id"],["supported_source_artifacts.id"]),sa.ForeignKeyConstraint(["processing_run_id"],["supported_processing_runs.id"]),sa.ForeignKeyConstraint(["raw_representation_id"],["evidence_typed_representations.id"]),sa.ForeignKeyConstraint(["normalized_representation_id"],["evidence_typed_representations.id"]),sa.ForeignKeyConstraint(["transformation_id"],["evidence_value_transformations.id"]))
 for name in ("evidence_timestamp_observations","evidence_processing_coverage_observations","evidence_omission_observations","evidence_processing_issues","evidence_partial_processing_observations"):
  op.create_table(name,sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("processing_run_id",sa.Uuid(),nullable=False),sa.Column("source_artifact_id",sa.Uuid(),nullable=False),sa.Column("observation",sa.JSON(),nullable=False),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["processing_run_id"],["supported_processing_runs.id"]),sa.ForeignKeyConstraint(["source_artifact_id"],["supported_source_artifacts.id"]))
 op.create_table("supported_normalized_records",*_scope(),sa.Column("evidence_source_id",sa.Uuid(),nullable=False),sa.Column("source_artifact_id",sa.Uuid(),nullable=False),sa.Column("processing_run_id",sa.Uuid(),nullable=False),sa.Column("parser_identity_id",sa.Uuid(),nullable=False),sa.Column("source_locator_id",sa.Uuid(),nullable=False),sa.Column("raw_value_observation_id",sa.Uuid(),nullable=False),sa.Column("normalized_value_observation_id",sa.Uuid()),sa.Column("timestamp_observation_id",sa.Uuid()),sa.Column("schema_fingerprint_observation_id",sa.Uuid(),nullable=False),sa.Column("limitations",sa.JSON(),nullable=False),sa.Column("admitted_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["tenant_id"],["security_tenants.id"]),sa.ForeignKeyConstraint(["case_id","tenant_id"],["security_cases.id","security_cases.tenant_id"]),sa.ForeignKeyConstraint(["source_artifact_id"],["supported_source_artifacts.id"]),sa.ForeignKeyConstraint(["processing_run_id"],["supported_processing_runs.id"]),sa.ForeignKeyConstraint(["parser_identity_id"],["evidence_parser_identities.id"]))
 op.create_table("supported_admission_decisions",*_scope(),sa.Column("candidate_id",sa.Uuid(),nullable=False),sa.Column("record_id",sa.Uuid()),sa.Column("outcome",sa.String(32),nullable=False),sa.Column("code",sa.String(128),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("authorization_reference",sa.Text()),sa.Column("promotion_reference",sa.Text()),sa.Column("integrity_approval_reference",sa.Text()),sa.Column("limitations",sa.JSON(),nullable=False),sa.ForeignKeyConstraint(["record_id"],["supported_normalized_records.id"]))
 op.create_table("supported_record_supersessions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("original_record_id",sa.Uuid(),nullable=False,unique=True),sa.Column("superseding_record_id",sa.Uuid(),nullable=False,unique=True),sa.Column("reason",sa.Text(),nullable=False),sa.Column("governing_reference",sa.Text(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("original_record_id <> superseding_record_id"),sa.ForeignKeyConstraint(["original_record_id"],["supported_normalized_records.id"]),sa.ForeignKeyConstraint(["superseding_record_id"],["supported_normalized_records.id"]))
def downgrade():
 for name in ("supported_record_supersessions","supported_admission_decisions","supported_normalized_records","evidence_partial_processing_observations","evidence_processing_issues","evidence_omission_observations","evidence_processing_coverage_observations","evidence_timestamp_observations","evidence_typed_value_observations","evidence_value_transformations","evidence_typed_representations","evidence_schema_fingerprint_observations","supported_source_locators","supported_source_artifacts","evidence_parser_identities","supported_processing_runs"):op.drop_table(name)
