"""candidate processing idempotency and forensic rerun persistence

Revision ID: 0005_processing_idempotency
Revises: 0004_candidate_supported_store
"""
from alembic import op
import sqlalchemy as sa
revision="0005_processing_idempotency";down_revision="0004_candidate_supported_store";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("processing_logical_requests",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("tenant_id",sa.Uuid(),nullable=False),sa.Column("case_id",sa.Uuid(),nullable=False),sa.Column("evidence_source_id",sa.Uuid(),nullable=False),sa.Column("source_artifact_id",sa.Uuid(),nullable=False),sa.Column("parser_id",sa.String(128),nullable=False),sa.Column("parser_version",sa.String(64),nullable=False),sa.Column("parser_contract_version",sa.String(64),nullable=False),sa.Column("artifact_family",sa.String(128),nullable=False),sa.Column("schema_profile_id",sa.String(128),nullable=False),sa.Column("processing_profile_id",sa.String(128),nullable=False),sa.Column("processing_profile_version",sa.String(64),nullable=False),sa.Column("operation",sa.String(128),nullable=False),sa.Column("controlled_input_digest",sa.String(64),nullable=False),sa.Column("authorization_reference",sa.Text(),nullable=False),sa.Column("idempotency_profile_id",sa.String(128),nullable=False),sa.Column("idempotency_profile_version",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(64),nullable=False),sa.Column("canonical_input_digest",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("limitations",sa.JSON(),nullable=False),sa.UniqueConstraint("tenant_id","case_id","evidence_source_id","source_artifact_id","operation","idempotency_profile_id","idempotency_profile_version","idempotency_key",name="uq_processing_active_exact_claim"),sa.ForeignKeyConstraint(["tenant_id"],["security_tenants.id"]),sa.ForeignKeyConstraint(["case_id","tenant_id"],["security_cases.id","security_cases.tenant_id"]),sa.ForeignKeyConstraint(["source_artifact_id"],["supported_source_artifacts.id"]))
 op.create_table("processing_execution_attempts",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("request_id",sa.Uuid(),nullable=False),sa.Column("attempt_number",sa.Integer(),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("ended_at",sa.DateTime(timezone=True)),sa.Column("status",sa.String(32),nullable=False),sa.Column("prior_run_id",sa.Uuid()),sa.Column("reason_code",sa.String(128)),sa.Column("limitations",sa.JSON(),nullable=False),sa.UniqueConstraint("request_id","attempt_number"),sa.ForeignKeyConstraint(["request_id"],["processing_logical_requests.id"]),sa.ForeignKeyConstraint(["prior_run_id"],["processing_execution_attempts.id"]),sa.CheckConstraint("attempt_number > 0"))
 op.create_table("processing_run_relationships",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("prior_run_id",sa.Uuid(),nullable=False),sa.Column("current_run_id",sa.Uuid(),nullable=False,unique=True),sa.Column("relationship_type",sa.String(64),nullable=False),sa.Column("reason_code",sa.String(128),nullable=False),sa.Column("explanation",sa.Text(),nullable=False),sa.Column("authorization_reference",sa.Text(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("limitations",sa.JSON(),nullable=False),sa.CheckConstraint("prior_run_id <> current_run_id"),sa.ForeignKeyConstraint(["prior_run_id"],["processing_execution_attempts.id"]),sa.ForeignKeyConstraint(["current_run_id"],["processing_execution_attempts.id"]))
def downgrade():
 for name in ("processing_run_relationships","processing_execution_attempts","processing_logical_requests"):op.drop_table(name)
